//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tulip.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_DIALOGTYPE                  127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_UMLTYPE                     130
#define ID_WINDOW_MANAGER               131
#define IDR_NETWORTYPE                  132
#define IDR_MENU_EDITOR_POPUP           133
#define IDR_FLOWCHTYPE                  134
#define IDD_NET_PROPERTY_DIALOG         136
#define IDB_BITMAP1                     137
#define IDB_NET_BITMAP_SYMBOL_ADSL      138
#define IDB_NET_BITMAP_SYMBOL_CLIENT    139
#define IDB_NET_BITMAP_SYMBOL_HUB       140
#define IDB_NET_BITMAP_SYMBOL_INTERNET  141
#define IDB_NET_BITMAP_SYMBOL_PRINTER   142
#define IDB_NET_BITMAP_SYMBOL_SERVER    143
#define IDD_FLOWCHART_DIALOG_PROPERTY_LABEL 144
#define IDD_FLOWCHART_DIALOG_LINK_TITLE 145
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDB_DARROW                      160
#define IDB_DFARROW                     161
#define IDB_INTERFACE                   162
#define IDB_LARROW                      163
#define IDB_LFARROW                     164
#define IDB_LRDIAMOND                   165
#define IDB_LRJOG                       166
#define IDB_NOTE                        167
#define IDB_PARTOF                      168
#define IDB_RARROW                      169
#define IDB_RFARROW                     170
#define IDB_UARROW                      171
#define IDB_UDDIAMOND                   172
#define IDB_UDJOG                       173
#define IDB_UFARROW                     174
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DIALOG_EXPORT               310
#define IDD_UML_DIALOG_PROPERTY_PACKAGE 431
#define IDD_UML_DIALOG_LINK_TITLE       432
#define IDD_UML_DIALOG_PROPERTY_LINK    432
#define IDD_UML_DIALOG_PROPERTY_LABEL   433
#define IDD_UML_DIALOG_PROPERTY_CLASS_ATTRIBUTE 434
#define IDI_UML_ICON_UP                 435
#define IDC_UML_CURSOR_DRAW             436
#define IDC_UML_CURSOR_ATTACH           437
#define IDC_UML_CURSOR_UP               438
#define IDD_UML_DIALOG_PROPERTY_CLASS   439
#define IDD_UML_DIALOG_PROPERTY_CLASS_OPERATION_PARAMETER 441
#define IDR_UML_MENU_PACKAGE_POPUP      442
#define IDD_UML_DIALOG_PROPERTY_INTERFACE 443
#define IDR_UML_MENU_CLASS_POPUP        443
#define IDD_UML_DIALOG_PROPERTY_EDITOR  444
#define IDR_UML_MENU_LINK               444
#define IDD_UML_DIALOG_PROPERTY_LIST_EDITOR 446
#define IDD_UML_DIALOG_PROPERTY_CLASS_DISPLAY 447
#define IDD_UML_DIALOG_GETTER_SETTER    449
#define IDD_UML_DIALOG_PROPERTY_CLASS_OPERATION 450
#define IDD_UML_DIALOG_PROPERTY_NOTE    451
#define IDD_UML_DIALOG_PROPERTY_TEMPLATE 452
#define IDC_NET_EDIT_TITLE              999
#define IDC_UML_EDIT_LINK_TITLE         1000
#define IDC_RADIO_ASSOCIATION           1002
#define IDC_RADIO_ACCESS                1003
#define IDC_RADIO5                      1004
#define IDC_RADIO6                      1005
#define IDC_EDIT_TEXT                   1006
#define IDC_EDIT_TYPE                   1007
#define IDC_BUTTON_FONT                 1008
#define IDC_BUTTON_COLOR                1009
#define IDC_BUTTON_VISIBILITY           1010
#define IDC_CHECK_UNIDIRECTIONAL        1011
#define IDC_EDIT_START_LABEL            1012
#define IDC_EDIT_END_LABEL              1013
#define IDC_RADIO_DEPENDENCY            1014
#define IDC_RADIO_INHERITANCE           1015
#define IDC_RADIO_COMPOSITION           1016
#define IDC_EDIT_SECONDARY_START_LABEL  1017
#define IDC_EDIT_SECONDARY_END_LABEL    1018
#define IDC_LIST_ATTRIBUTES             1020
#define IDC_LIST_OPERATIONS             1021
#define IDC_BUTTON_ADD_ATTRIBUTE        1022
#define IDC_BUTTON_ADD_OPERATION        1024
#define IDC_EDIT_NAME                   1027
#define IDC_CHECK_ABSTRACT              1030
#define IDC_CHECK_STATIC                1031
#define IDC_LIST_PARAMETERS             1032
#define IDC_BUTTON_ADD                  1033
#define IDC_EDIT_MULTIPLICITY           1042
#define IDC_EDIT_INITIAL_VALUE          1043
#define IDC_EDIT_PROPERTY_LIST          1044
#define IDC_CHECK_CONST                 1048
#define IDC_RADIO_PARTOF                1051
#define IDC_CHECK_GRID                  1053
#define IDC_CHECK_SHOW_GRID             1054
#define IDC_CHECK_ONLY_PUBLIC           1055
#define IDC_CHECK_NO_MARKERS            1056
#define IDC_RADIO_INVISIBLE             1058
#define IDC_CHECK_NO_ATTRIBUTES         1066
#define IDC_CHECK_NO_OPERATIONS         1067
#define IDC_CHECK_NO_ATTRIBUTE_NAMES    1069
#define IDC_LIST_TAGS                   1070
#define IDC_EDIT_VALUE                  1073
#define IDC_BUTTON_DELETE               1075
#define IDC_BUTTON_PROPERTY_LIST        1076
#define IDC_BUTTON_UPDATE               1076
#define IDC_BUTTON_AUTO_GENERATE        1079
#define IDC_BUTTON_AUTO_GENERATE2       1080
#define IDC_CHECK_IN                    1080
#define IDC_CHECK_OUT                   1081
#define IDC_CHECK_REFERENCE             1082
#define IDC_COMBO_STEREOTYPE            1083
#define IDC_COMBO_TAG                   1084
#define IDC_EDIT_GETTER                 1089
#define IDC_EDIT_SETTER                 1090
#define IDC_CHECK_SHOW_MARGINS          1092
#define IDC_RADIO_INTERFACE             1093
#define IDC_BUTTON_CLOSE                1094
#define IDC_EDIT_PARAMETER              1096
#define IDC_RADIO_CPP                   2001
#define IDC_RADIO_EMF                   2002
#define IDC_RADIO_HTML                  2003
#define IDC_CHECK_ONLY_H                2004
#define IDC_CHECK_STRIP_LEADING         2005
#define IDC_STATIC_STRIP_INFO           2006
#define IDC_DIALOG_EDIT_WIDTH           3000
#define IDC_DIALOG_EDIT_HEIGHT          3001
#define IDC_DIALOG_EDIT_GRID_WIDTH      3002
#define IDC_DIALOG_EDIT_GRID_HEIGHT     3003
#define IDC_DIALOG_EDIT_LEFT            3004
#define IDC_DIALOG_EDIT_TOP             3005
#define IDC_DIALOG_EDIT_RIGHT           3006
#define IDC_DIALOG_EDIT_BOTTOM          3007
#define IDC_DIALOG_EDIT_TITLE           3008
#define IDC_DIALOG_EDIT_NAME            3010
#define IDD_DIALOG_SETTINGS             3130
#define IDD_DIALOG_BUTTON_PROPERTIES    3131
#define IDD_DIALOG_EDIT_PROPERTIES      3132
#define IDC_SETTINGS                    22774
#define ID_DIALOG_ADD_BUTTON            22775
#define ID_DIALOG_ADD_EDIT              22776
#define ID_DIALOG_ADD_STATIC            22777
#define ID_DIALOG_ADD_CHECKBOX          22794
#define ID_DIALOG_ADD_RADIOBUTTON       22795
#define ID_DIALOG_ADD_LISTBOX           22796
#define ID_DIALOG_ADD_GROUPBOX          22798
#define ID_DIALOG_ADD_COMBOBOX          22801
#define ID_MARGINS                      22806
#define ID_RESTRAIN                     22807
#define ID_LEFT_ALIGN                   22808
#define ID_RIGHT_ALIGN                  22809
#define ID_TOP_ALIGN                    22810
#define ID_BOTTOM_ALIGN                 22811
#define ID_MAKE_SAME_SIZE               22812
#define ID_UP                           22813
#define ID_DOWN                         22814
#define ID_FRONT                        22815
#define ID_BOTTOM                       22816
#define ID_DIALOG_ADD_NONE              22819
#define ID_BUTTON_MULTIDRAW             22821
#define IDC_FLOWCHART_EDIT_LINK_TITLE   31000
#define IDM_FLOWCHART_LINK_DIRECTION    31001
#define IDM_FLOWCHART_LINK_PROPERTIES   31002
#define IDM_FLOWCHART_UNLINK            31003
#define IDM_FLOWCHART_LINK              31004
#define IDS_FLOWCHART_BOX               31446
#define IDS_FLOWCHART_CONDITION         31447
#define IDS_FLOWCHART_CONNECTOR         31448
#define IDS_FLOWCHART_IO                31449
#define IDS_FLOWCHART_TERMINATOR        31450
#define IDS_FLOWCHART_LABEL             31451
#define ID_FLOWCHART_BUTTON_LINE        31771
#define ID_FLOWCHART_BUTTON_BOX         31772
#define ID_FLOWCHART_LINK_LABEL         31773
#define ID_FLOWCHART_FLIP_LINK          31774
#define ID_FLOWCHART_BUTTON_CONNECTOR   31775
#define ID_FLOWCHART_BUTTON_CONDITION   31776
#define ID_FLOWCHART_BUTTON_START       31777
#define ID_FLOWCHART_BUTTON_IO          31779
#define ID_FLOWCHART_BUTTON_ARROW       31780
#define ID_FLOWCHART_BUTTON_LABEL       31782
#define ID_BUTTON_CLASS                 32771
#define ID_BUTTON_LINK                  32772
#define ID_BUTTON_NOTE                  32773
#define ID_BUTTON_PACKAGE               32774
#define ID_BUTTON_LABEL                 32775
#define ID_BUTTON_INTERFACE             32776
#define ID_BUTTON_DISPLAY_PROPERTIES    32778
#define ID_EXPORT                       32779
#define ID_PROPERTY                     32780
#define ID_ZOOM                         32781
#define ID_ZOOM_25                      32782
#define ID_ZOOM_50                      32783
#define ID_ZOOM_100                     32784
#define ID_ZOOM_150                     32785
#define ID_ZOOM_200                     32786
#define ID_FLIP_LINK                    32787
#define ID_SHOW_GRID                    32788
#define ID_SNAP                         32789
#define ID_IMPORT                       32791
#define ID_EDIT_DELETE                  32792
#define ID_BUTTON_TEMPLATE              32796
#define ID_FILE_NEW_UML                 32800
#define ID_FILE_NEW_FLOWCHART           32801
#define ID_FILE_NEW_NET                 32802
#define ID_UMLCONTEXT                   32803
#define ID_NETCONTEXT                   32804
#define ID_FLOWCHARTCONTEXT             32805
#define ID_FLOW                         32811
#define ID_FILE_NEW_DIALOG              32812
#define ID_DIALOGCONTEXT                32818
#define ID_EXPORT_EMF                   32819
#define ID_EXPORT_HTML                  32820
#define ID_EXPORT_CPP                   32821
#define ID_DUPLICATE                    32823
#define ID_UML_OPEN_PACKAGE             32824
#define IDM_NETWORKEDITOR_LINK          33442
#define IDM_NETWORKEDITOR_UNLINK        33445
#define IDS_UML_CLASS                   33447
#define IDS_UML_PACKAGE                 33448
#define IDS_UML_NOTE                    33449
#define IDS_UML_LABEL                   33450
#define IDS_UML_INTERFACE               33451
#define IDS_UML_DELETE_OPERATION        33453
#define IDS_UML_DELETE_ATTRIBUTE        33454
#define IDS_UML_CLASS_MUST_HAVE_A_NAME  33455
#define IDS_UML_ATTRIBUTE_MUST_HAVE_A_NAME 33456
#define IDS_UML_OPERATION_MUST_HAVE_A_NAME 33457
#define IDS_UML_ATTRIBUTE_MUST_HAVE_A_TYPE 33458
#define IDS_UML_OPERATION_MUST_HAVE_A_TYPE 33459
#define IDS_UML_PARAMETER_MUST_HAVE_A_TYPE 33460
#define IDS_UML_PARAMETER_MUST_HAVE_A_NAME 33461
#define IDS_UML_PACKAGE_EXISTS          33463
#define IDS_UML_SELECT_FOLDER           33464
#define IDS_UML_PROPERTY_LIST_TAG_MUST_HAVE_A_VALUE 33465
#define IDS_UML_CREATEGETTERS_SETTERS   33466
#define IDS_UML_MISSING_BRACKET         33467
#define IDS_UML_MALFORMED_COMMENT       33468
#define IDS_UML_CREATECTOR_DTOR         33469
#define IDS_UML_GETTER_MUST_HAVE_A_NAME 33470
#define IDS_UML_SETTER_MUST_HAVE_A_NAME 33471
#define IDS_UML_GETSET_DEFINED          33472
#define IDS_UML_MUST_SELECT_AN_ATTRIBUTE 33473
#define ID_NET_BUTTON_ADD_SERVER        34771
#define ID_NET_BUTTON_ADD_CLIENT        34772
#define ID_NET_BUTTON_ADD_PRINTER       34773
#define ID_NET_BUTTON_ADD_HUB           34774
#define ID_NET_BUTTON_ADD_MODEM         34775
#define ID_NET_BUTTON_ADD_INTERNET      34776
#define ID_NET_BUTTON_ADD_LABEL         34777
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_REDO                    0xE12C
#define ID_EDIT_GROUP                   0xE12D
#define ID_EDIT_UNGROUP                 0xE12E
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_INDICATOR_EXT                0xE700
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define ID_INDICATOR_OVR                0xE704
#define ID_INDICATOR_REC                0xE705
#define ID_VIEW_TOOLBAR                 0xE800
#define AFX_IDS_SCSIZE                  0xEF00
#define AFX_IDS_SCMOVE                  0xEF01
#define AFX_IDS_SCMINIMIZE              0xEF02
#define AFX_IDS_SCMAXIMIZE              0xEF03
#define AFX_IDS_SCNEXTWINDOW            0xEF04
#define AFX_IDS_SCPREVWINDOW            0xEF05
#define AFX_IDS_SCCLOSE                 0xEF06
#define AFX_IDS_SCRESTORE               0xEF12
#define AFX_IDS_SCTASKLIST              0xEF13
#define AFX_IDS_MDICHILD                0xEF1F
#define AFX_IDS_PREVIEW_CLOSE           0xF005
#define IDS_UML_EXPORT_FINISHED         61446
#define IDS_UML_TEMPLATE                61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        312
#define _APS_NEXT_COMMAND_VALUE         32826
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
